# # This is a basic workflow to help you get started with Actions

# name: Build & Deploy

# # Controls when the workflow will run
# on:
#   # Triggers the workflow on push  and pull requests events
#   push:
#     branches:
#       - main
#       - master
#       - sandbox
#   pull_request:
#     branches:
#       - main
#       - master
#       - sandbox

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   # This workflow contains a single job called "build"
#   build:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         os: [ubuntu-latest]
#         node: [16]
#         npm: [8]
#         include:
#          - os: ubuntu-latest
#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v2
#       # Setup node
#       - uses: actions/setup-node@v2.4.1
#         with:
#           node-version: '16'
#           cache: 'npm'
#           cache-dependency-path: '**/package-lock.json'
#       - name: Download local dependencies
#         run: npm install --no-audit
#       - name: Suitecloud set production account
#         if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
#         shell: bash
#         env:
#           ACCOUNT_PROD: ${{ secrets.ACCOUNT_PROD }}
#           TOKEN_PROD: ${{ secrets.TOKEN_PROD }}
#           TOKEN_SECRET_PROD: ${{ secrets.TOKEN_SECRET_PROD }}
#         run: suitecloud account:savetoken --authid DeployWithGHAction --account $ACCOUNT_PROD --tokenid $TOKEN_PROD --tokensecret $TOKEN_SECRET_PROD
#       - name: Suitecloud set sandbox account
#         if: github.ref == 'refs/heads/sandbox'
#         shell: bash
#         env:
#           ACCOUNT_SB: ${{ secrets.ACCOUNT_SB }}
#           TOKEN_SB: ${{ secrets.TOKEN_SB }}
#           TOKEN_SECRET_SB: ${{ secrets.TOKEN_SECRET_SB }}
#         run: suitecloud account:savetoken --authid DeployWithGHAction --account $ACCOUNT_SB --tokenid $TOKEN_SB --tokensecret $TOKEN_SECRET_SB
#       - name: Upload complied files from build folder
#         run: npm run deploy
